### ISSUE TITLE
New method: github metrics

### ISSUE THREAD

**Issue by matentzn** [gouttegd/grainyhead#4]
As an ontology developer, I need to quantify the impact of external stakeholders and internal providers. To do that, I would like to see the following metrics:

Given a date range `--from`...`--to`,
- How many issues were opened (internal/external)
- How many pull requests were opened (internal/external)
- How many issues were closed (internal/external)
- How many pull requests were closed (internal/external)
- How many contributors (internal/external): a contributor is someone that opened/closed and issue/pr or left a comment somewhere
- How many comments were made (internal/external)
- Less interesting, but still interesting: How many commits (external/internal)
- Number of releases
- Super cool but not necessary: number of external issues/pull requests mentioning issues/pull requests from the rep

**Comment by matentzn** [comment]
In the end, we would want to use this method also to quantify the impact on an individual contributor level, not just team (external/internal).

**Comment by gouttegd** [comment]
There is now a `metrics` subcommand to get the stats listed above (except the last one).

By default, it gives the metrics computed over the last 6 months.

Example output (here with the Uberon repository):

| Event                | Total | Internal | External | Ext. (%) |
| -------------------- | ----- | -------- | -------- | -------- |
| Issues opened        |   141 |       83 |       58 |    41.13 |
| Issues closed        |   516 |      515 |        1 |     0.19 |
| Pull requests opened |    98 |       96 |        2 |     2.04 |
| Pull requests closed |    94 |       94 |        0 |     0.00 |
| Pull requests merged |    70 |       70 |        0 |     0.00 |
| Comments             |  1079 |      990 |       89 |     8.25 |
| Commits              |   189 |      151 |       38 |    20.11 |
| Contributors         |    43 |       14 |       29 |    67.44 |
| Releases             |     4 |          |          |          |

**Comment by gouttegd** [comment]
The command is quite slow (~15 seconds with the Uberon repository). Most of the time is spent getting the *events* needed to to compute the number of issues/PRs closed/merged; unfortunately the Github API does not allow to get only the events that occurred over a given time period, so we need to fetch *all* the events over the lifetime of the repository, which takes quite some time…

**Comment by matentzn** [comment]
Oh my... this is so amazing!! Can't wait to try it!!

**Comment by matentzn** [comment]
Can you give the whole command I need to run? :)

**Comment by gouttegd** [comment]
Assuming you have a config file like the following:

```
[default]
repository = https://github.com/obophenotype/uberon
token = <your access token>
```

To get the stats for the period between January 1st, 2021 and June 30th, 2021:
```sh
$ grh metrics --team=uberon-cl-curators --from=2021-01-01 --to=2021-06-30
```

Or simpler, to get the period over the last 6 months:
```sh
$ grh metrics --team=uberon-cl-curators
```

Or to get the last 2 years:
```sh
$ grh metrics --team=uberon-cl-curators --from=2y
```

**Comment by matentzn** [comment]
This is too awesome! I love it so much :)

I will document some of my observations and problems in the following.

- [ ] As I am running this for dozens of ontologies, it would be better if "repository" was a parameter passed to grainyhead

**Comment by matentzn** [comment]
https://github.com/pato-ontology/pato

```
PYTHONPATH=. python fbcam/grainyhead/main.py metrics --team=pato-community --from=2020-06-30 --to=2020-08-25
From 2020-06-30 to 2020-08-25
```

| Event                | Total | Internal | External | Ext. (%) |
| -------------------- | ----- | -------- | -------- | -------- |
| Issues opened        |     6 |        1 |        5 |    83.33 |
| Issues closed        |     4 |        3 |        1 |    25.00 |
| Pull requests opened |     4 |        4 |        0 |     0.00 |
| Pull requests closed |     5 |        4 |        1 |    20.00 |
| Pull requests merged |     4 |        4 |        0 |     0.00 |
| Comments             |    18 |       13 |        5 |    27.78 |
| Commits              |     9 |        9 |        0 |     0.00 |
| Contributors         |    12 |        6 |        6 |    50.00 |
| Releases             |     1 |          |          |          |

**Comment by matentzn** [comment]
https://github.com/obophenotype/cell-ontology

```
PYTHONPATH=. python fbcam/grainyhead/main.py metrics --team=uberon-cl-curators --from=2020-06-30 --to=2020-08-25
```

| Event                | Total | Internal | External | Ext. (%) |
| -------------------- | ----- | -------- | -------- | -------- |
| Issues opened        |     4 |        1 |        3 |    75.00 |
| Issues closed        |     2 |        1 |        1 |    50.00 |
| Pull requests opened |     5 |        5 |        0 |     0.00 |
| Pull requests closed |     3 |        3 |        0 |     0.00 |
| Pull requests merged |     3 |        3 |        0 |     0.00 |
| Comments             |    23 |       18 |        5 |    21.74 |
| Commits              |    32 |       32 |        0 |     0.00 |
| Contributors         |    10 |        6 |        4 |    40.00 |
| Releases             |     0 |          |          |          |

**Comment by matentzn** [comment]
https://github.com/obophenotype/uberon

```
PYTHONPATH=. python fbcam/grainyhead/main.py metrics --team=uberon-cl-curators --from=2020-06-30 --to=2020-08-25
```

```
Traceback (most recent call last):
  File "fbcam/grainyhead/main.py", line 296, in <module>
    grh()
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click_shell/core.py", line 164, in invoke
    ret = super(Shell, self).invoke(ctx)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "fbcam/grainyhead/main.py", line 233, in metrics
    metrics = grh.repository.get_metrics(start, end, team)
  File "/Users/matentzn/ws/grainyhead/fbcam/grainyhead/repository.py", line 134, in get_metrics
    issues_closes = [e for e in self.events
  File "/Users/matentzn/ws/grainyhead/fbcam/grainyhead/repository.py", line 78, in events
    self._events = self._fetch(self._api.issues.list_events_for_repo,
  File "/Users/matentzn/ws/grainyhead/fbcam/grainyhead/repository.py", line 194, in _fetch
    things = pages(apicall, last_page, **apiargs).concat()
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/ghapi/page.py", line 69, in pages
    return parallel(_call_page, range(1,n_pages+1), oper=oper, per_page=per_page, args=args, kwargs=kwargs,
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/fastcore/parallel.py", line 123, in parallel
    return L(r)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/fastcore/foundation.py", line 97, in __call__
    return super().__call__(x, *args, **kwargs)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/fastcore/foundation.py", line 105, in __init__
    items = listify(items, *rest, use_list=use_list, match=match)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/fastcore/basics.py", line 56, in listify
    elif is_iter(o): res = list(o)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
    yield fs.pop().result()
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/fastcore/parallel.py", line 58, in _call
    return g(item)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/ghapi/page.py", line 64, in _call_page
    return oper(*args, per_page=per_page, page=i, **kwargs)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/ghapi/core.py", line 63, in __call__
    return self.client(self.path, self.verb, headers=headers, route=route_p, query=query_p, data=data_p)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/ghapi/core.py", line 108, in __call__
    res,self.recv_hdrs = urlsend(path, verb, headers=headers or None, debug=self.debug, return_headers=True,
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/fastcore/net.py", line 212, in urlsend
    return urlread(req, return_json=return_json, return_headers=return_headers)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/fastcore/net.py", line 111, in urlread
    with urlopen(url, data=data, headers=headers, **kwargs) as u: res,hdrs = u.read(),u.headers
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/http/client.py", line 467, in read
    s = self._safe_read(self.length)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/http/client.py", line 608, in _safe_read
    data = self.fp.read(amt)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 54] Connection reset by peer
```

**Comment by matentzn** [comment]
https://github.com/obophenotype/human-phenotype-ontology

```
PYTHONPATH=. python fbcam/grainyhead/main.py metrics --team=human-phenotype --from=2020-06-30 --to=2020-08-25
```

```
Traceback (most recent call last):
  File "fbcam/grainyhead/main.py", line 296, in <module>
    grh()
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click_shell/core.py", line 164, in invoke
    ret = super(Shell, self).invoke(ctx)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "fbcam/grainyhead/main.py", line 233, in metrics
    metrics = grh.repository.get_metrics(start, end, team)
  File "/Users/matentzn/ws/grainyhead/fbcam/grainyhead/repository.py", line 134, in get_metrics
    issues_closes = [e for e in self.events
  File "/Users/matentzn/ws/grainyhead/fbcam/grainyhead/repository.py", line 78, in events
    self._events = self._fetch(self._api.issues.list_events_for_repo,
  File "/Users/matentzn/ws/grainyhead/fbcam/grainyhead/repository.py", line 194, in _fetch
    things = pages(apicall, last_page, **apiargs).concat()
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/ghapi/page.py", line 69, in pages
    return parallel(_call_page, range(1,n_pages+1), oper=oper, per_page=per_page, args=args, kwargs=kwargs,
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/fastcore/parallel.py", line 123, in parallel
    return L(r)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/fastcore/foundation.py", line 97, in __call__
    return super().__call__(x, *args, **kwargs)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/fastcore/foundation.py", line 105, in __init__
    items = listify(items, *rest, use_list=use_list, match=match)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/fastcore/basics.py", line 56, in listify
    elif is_iter(o): res = list(o)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
    yield fs.pop().result()
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/fastcore/parallel.py", line 58, in _call
    return g(item)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/ghapi/page.py", line 64, in _call_page
    return oper(*args, per_page=per_page, page=i, **kwargs)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/ghapi/core.py", line 63, in __call__
    return self.client(self.path, self.verb, headers=headers, route=route_p, query=query_p, data=data_p)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/ghapi/core.py", line 108, in __call__
    res,self.recv_hdrs = urlsend(path, verb, headers=headers or None, debug=self.debug, return_headers=True,
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/fastcore/net.py", line 212, in urlsend
    return urlread(req, return_json=return_json, return_headers=return_headers)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/fastcore/net.py", line 111, in urlread
    with urlopen(url, data=data, headers=headers, **kwargs) as u: res,hdrs = u.read(),u.headers
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/http/client.py", line 467, in read
    s = self._safe_read(self.length)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/http/client.py", line 608, in _safe_read
    data = self.fp.read(amt)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 54] Connection reset by peer
```

**Comment by matentzn** [comment]
https://github.com/monarch-initiative/mondo

```
PYTHONPATH=. python fbcam/grainyhead/main.py metrics --team=monarch-ontology-team --from=2020-06-30 --to=2020-08-25
```

```
Does not terminate! (After 3 hours, still running)
```

**Comment by gouttegd** [comment]
Seems to work now for Mondo:

```
$ grh -s mondo metrics --from 1y --team monarch-ontology-team
WARNING:root:Cannot get team data (possibly due to insufficient access rights)
From 2020-12-01 to 2021-12-01

| Event                | Total | Internal | External | Ext. (%) |
| -------------------- | ----- | -------- | -------- | -------- |
| Issues opened        |   660 |        0 |      660 |   100.00 |
| Issues closed        |   850 |        0 |      850 |   100.00 |
| Pull requests opened |  1011 |        0 |     1011 |   100.00 |
| Pull requests closed |  1023 |        0 |     1023 |   100.00 |
| Pull requests merged |   938 |        0 |      938 |   100.00 |
| Comments             |  2458 |        0 |     2458 |   100.00 |
| Commits              |  3216 |        0 |     3216 |   100.00 |
| Contributors         |    85 |        0 |       85 |   100.00 |
| Releases             |    15 |          |          |          |
```

And for HPO, though it is even slower than all other ontologies (here asking for one month only):

```
% grh -s hpo metrics --from 1m --team human-phenotype
From 2021-11-01 to 2021-12-01

| Event                | Total | Internal | External | Ext. (%) |
| -------------------- | ----- | -------- | -------- | -------- |
| Issues opened        |    52 |       21 |       31 |    59.62 |
| Issues closed        |    40 |       40 |        0 |     0.00 |
| Pull requests opened |     1 |        1 |        0 |     0.00 |
| Pull requests closed |     1 |        1 |        0 |     0.00 |
| Pull requests merged |     1 |        1 |        0 |     0.00 |
| Comments             |    61 |       44 |       17 |    27.87 |
| Commits              |     7 |        7 |        0 |     0.00 |
| Contributors         |    16 |        4 |       12 |    75.00 |
| Releases             |     0 |          |          |          |
```

**Comment by matentzn** [comment]
Amazing, how can I "install" grainyhead to get the grh command?

**Comment by gouttegd** [comment]
```sh
$ python -m pip install git+https://github.com/gouttegd/grainyhead
```

Should install _grainyhead_ and its dependencies in your per-user Python directory, and place the `grh` script in your PATH.

(Feel free to do that in a virtualenv if you’d rather avoid modifying your per-user Python installation.)

**Comment by gouttegd** [comment]
At some point I’ll make a proper release to PyPI so it will be possible to do `python -m pip install grainyhead`, but I feel it’s still a bit too early to do that.
