### ISSUE TITLE
IncompleteRead for large ontologies 

### ISSUE THREAD

**Issue by matentzn** [gouttegd/grainyhead#7]
I keep getting IncompleteRead for large ontologies like Uberon and Mondo. PATO and CL work fine

```
grh -s mondo metrics --from=1y
```

```
Traceback (most recent call last):
  File "/Users/matentzn/opt/anaconda3/bin/grh", line 8, in <module>
    sys.exit(grh())
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click_shell/core.py", line 164, in invoke
    ret = super(Shell, self).invoke(ctx)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/fbcam/grainyhead/main.py", line 233, in metrics
    metrics = grh.repository.get_metrics(start, end, team)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/fbcam/grainyhead/repository.py", line 178, in get_metrics
    commits = [c for c in self.commits
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/fbcam/grainyhead/repository.py", line 88, in commits
    self._commits = self._fetch(self._api.repos.list_commits,
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/fbcam/grainyhead/repository.py", line 204, in _fetch
    things = pages(apicall, last_page, **apiargs).concat()
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/ghapi/page.py", line 69, in pages
    return parallel(_call_page, range(1,n_pages+1), oper=oper, per_page=per_page, args=args, kwargs=kwargs,
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/fastcore/parallel.py", line 123, in parallel
    return L(r)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/fastcore/foundation.py", line 97, in __call__
    return super().__call__(x, *args, **kwargs)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/fastcore/foundation.py", line 105, in __init__
    items = listify(items, *rest, use_list=use_list, match=match)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/fastcore/basics.py", line 56, in listify
    elif is_iter(o): res = list(o)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
    yield fs.pop().result()
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/fastcore/parallel.py", line 58, in _call
    return g(item)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/ghapi/page.py", line 64, in _call_page
    return oper(*args, per_page=per_page, page=i, **kwargs)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/ghapi/core.py", line 63, in __call__
    return self.client(self.path, self.verb, headers=headers, route=route_p, query=query_p, data=data_p)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/ghapi/core.py", line 108, in __call__
    res,self.recv_hdrs = urlsend(path, verb, headers=headers or None, debug=self.debug, return_headers=True,
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/fastcore/net.py", line 212, in urlsend
    return urlread(req, return_json=return_json, return_headers=return_headers)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/fastcore/net.py", line 111, in urlread
    with urlopen(url, data=data, headers=headers, **kwargs) as u: res,hdrs = u.read(),u.headers
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/http/client.py", line 467, in read
    s = self._safe_read(self.length)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/http/client.py", line 610, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(403422 bytes read, 29814 more expected)
```

**Comment by gouttegd** [comment]
Sill working fine here…

I think a new approach is needed. What I imagine is:

* At the first invocation on a given repository, download *everything* and store locally. Retry failed downloads if needed, add waiting times between downloads if it helps avoiding the rate-limiting measures. This may take a while for large repos such as Mondo, but will need to be done once.
* On subsequent invocations, find a way to download *only* what we don’t already have locally.
* Allow to work in complete “offline” mode: if we have a local copy that is not too old (say, last update was less than a week ago), compute the metrics on the locally cached data without even trying to fetch anything from GitHub, unless the user explicitly requests a refresh.

**Comment by matentzn** [comment]
I think being able to point to a local checkout rather than the github repo would be _perfect_. However, this may be super difficult to implement, depending on the APIs you were using?

**Comment by gouttegd** [comment]
When I say “local copy”, I am not referring to a checkout in the Git sense of the term. There’s no way we can extract all the informations we need from a Git local copy (the only thing we can get from that are the commits; issues, PRs, comments, releases, etc. can only be obtained from GitHub directly).

The “local copy” or “cache” will simply be a folder containing a JSON representation of all the data we get from GitHub.

Regarding the implementation, I foresee two tricky bits:

* The API does not always allow to ask for “only the events after that date” – it does for some objects, such as issues, but not for some others, such as PR merge events. So we need to ask for the data in newer-first order, download them in chunks, and stop downloading as soon as we encounter objects that are already past the cutoff date. Not really difficult – that‘s basically what I did two days ago for the PR merge events (this is how I got grh to work-for-me on Mondo) –, just cumbersome.
* Issues and PRs are a tricky case because they can be updated at anytime. When we refresh the cache, we can easily get _new_ issues and PRs, but I am not sure how we can get _updates_ (new comments, status changes, labels, etc.) to older issues and PRs that we already have in cache. We’ll see.

(While we are at it, I want to be on record saying that the GitHub API has been designed by braindead monkeys.)

Anyway… estimated time for the implementation of the above: anytime between next week and 2027.

**Comment by matentzn** [comment]
Hhahah.. We are playing the long game :)

**Comment by gouttegd** [comment]
@matentzn Can you upgrade your copy of _grainyhead_ and try running again the `metrics` command on Mondo and Uberon?

I’ve added a basic file cache as discussed above. The first invocation on any given repository takes a while (we download _everything_; that means ~100 Mb of data for Uberon, ~300 Mb for Mondo), but _if_ it works, then no further network access will be needed no matter how many times you invoke the command, until the cache is more than 30 days old (this duration is not configurable for now, will be in the future).

**Comment by matentzn** [comment]
Works now!
